In [1]:
# Slicing = selecting a portion (part) of an array using indexes.
# Option 01 = arr[start:end:step] [N.B.: ending index is exclusive]

In [2]:
import numpy as np

In [3]:

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [4]:
# arr[start:end:step] [N.B.: ending index is exclusive]

In [5]:
arr[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
arr[0:4:2] # returns the rows frm 0 to 3, but only the 0th and 2nd rows

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [9]:
arr[::2] # will return as same as before

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [10]:
arr[::3] # will return the 0th and 3th rows

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [11]:
arr[::-1] # returns all the rows in reverse

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [12]:
arr[::-2] # the rows are in reverse and returning the second one

array([[13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [13]:
arr[:, 0] # returns the entire column 0

array([ 1,  5,  9, 13])

In [14]:
arr[:, 1] # returns the entire column 1

array([ 2,  6, 10, 14])

In [15]:
arr[:, -1] # returns the entire last column

array([ 4,  8, 12, 16])

In [16]:
arr[:, 0:3] # will return the elements of all rows, column (0, 1, 2)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [17]:
arr[0:2, 0:2] # returns the first 2 rows and first 2 cols; 4X4 matrix

array([[1, 2],
       [5, 6]])

In [18]:
arr[0:3, 0:3] # will return the elements of rows (0, 1, 2) and column (0, 1, 2)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [19]:
arr[1:3, 0:2] # returns the elements of rows (1, 2) and columns (0, 1)

array([[ 5,  6],
       [ 9, 10]])

In [20]:
arr[0:3:2, 0:4:2] # returns the elements of rows (0, 2) and columns (0, 2)

array([[ 1,  3],
       [ 9, 11]])

In [21]:
arr[0:3:2, 0:4:3] # returns the elements of rows (0, 2) and columns (0, 3)

array([[ 1,  4],
       [ 9, 12]])

In [22]:
arr[::-1, ::-1] # all the rows and columns are reversed

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [23]:
arr[::-1, ::-2] # all the rows and cols are reversed but only the 2nd last columns are return

array([[16, 14],
       [12, 10],
       [ 8,  6],
       [ 4,  2]])