In [1]:
import numpy as np

In [2]:
# Scalar Arighmatic

In [3]:
arr = np.array([1,2,3])

In [4]:
arr+1 # array([2, 3, 4]); adds 1 to all the elements

array([2, 3, 4])

In [5]:
arr-2

array([-1,  0,  1])

In [6]:
arr*2

array([2, 4, 6])

In [7]:
arr/2

array([0.5, 1. , 1.5])

In [8]:
arr**4

array([ 1, 16, 81])

In [9]:
# Vectorized Math Functions

In [10]:
np.sqrt(arr) # square root of all the array element

array([1.        , 1.41421356, 1.73205081])

In [11]:
# round() = Rounds to nearest integer [4.6 → 5, 4.4 → 4]
# floor() = Always rounds down [4.9 → 4]
# ceil() = Always rounds up  [4.1 → 5]

In [12]:
arr = np.array([1.34, 2.78, 3.50])

In [13]:
np.round(arr) # 1.34 → 1, 2.78 → 3, and 3.50 → 4

array([1., 3., 4.])

In [14]:
np.floor(arr) # 1.34 → 1, 2.78 → 2, and 3 → 4

array([1., 2., 3.])

In [15]:
np.ceil(arr) # 1.34 → 2, 2.78 → 3, and 3.50 → 4

array([2., 3., 4.])