In [202]:
import numpy as np

In [203]:
# Scalar Arighmatic

In [204]:
arr = np.array([1,2,3])

In [205]:
arr+1 # array([2, 3, 4]); adds 1 to all the elements

array([2, 3, 4])

In [206]:
arr-2

array([-1,  0,  1])

In [207]:
arr*2

array([2, 4, 6])

In [208]:
arr/2

array([0.5, 1. , 1.5])

In [209]:
arr**4

array([ 1, 16, 81])

In [210]:
# Vectorized Math Functions

In [211]:
np.sqrt(arr) # square root of all the array element

array([1.        , 1.41421356, 1.73205081])

In [212]:
# round() = Rounds to nearest integer [4.6 → 5, 4.4 → 4]
# floor() = Always rounds down [4.9 → 4]
# ceil() = Always rounds up  [4.1 → 5]

In [213]:
arr = np.array([1.34, 2.78, 3.50])

In [214]:
np.round(arr) # 1.34 → 1, 2.78 → 3, and 3.50 → 4

array([1., 3., 4.])

In [215]:
np.floor(arr) # 1.34 → 1, 2.78 → 2, and 3 → 4

array([1., 2., 3.])

In [216]:
np.ceil(arr) # 1.34 → 2, 2.78 → 3, and 3.50 → 4

array([2., 3., 4.])

In [217]:
np.pi # will return the value of pi = 3.1416....

3.141592653589793

In [218]:
# Excercise
# Given array is the list of radius of circles
# Find the area of the circles.

In [219]:

radius = np.array([2,3,4])
np.pi*radius**2

array([12.56637061, 28.27433388, 50.26548246])

In [220]:
# Element-wise arithmatic

In [221]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [222]:
arr1 + arr2

array([5, 7, 9])

In [223]:
arr1 - arr2

array([-3, -3, -3])

In [224]:
arr1 * arr2

array([ 4, 10, 18])

In [225]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [226]:
arr1 ** arr2

array([  1,  32, 729])

In [227]:
# Comparison Operator

In [228]:
scores = np.array([32, 45, 67, 87, 23, 56, 82, 96, 87, 99, 100])

In [229]:
scores >= 40

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [230]:
scores < 40

array([ True, False, False, False,  True, False, False, False, False,
       False, False])

In [231]:
scores[scores < 40]

array([32, 23])

In [232]:
scores[scores < 40] = 0
scores

array([  0,  45,  67,  87,   0,  56,  82,  96,  87,  99, 100])