In [1]:
import numpy as np

In [2]:
# Scalar Arighmatic

In [3]:
arr = np.array([1,2,3])

In [4]:
arr+1 # array([2, 3, 4]); adds 1 to all the elements

array([2, 3, 4])

In [5]:
arr-2

array([-1,  0,  1])

In [6]:
arr*2

array([2, 4, 6])

In [7]:
arr/2

array([0.5, 1. , 1.5])

In [8]:
arr**4

array([ 1, 16, 81])

In [9]:
# Vectorized Math Functions

In [10]:
np.sqrt(arr) # square root of all the array element

array([1.        , 1.41421356, 1.73205081])

In [11]:
# round() = Rounds to nearest integer [4.6 → 5, 4.4 → 4]
# floor() = Always rounds down [4.9 → 4]
# ceil() = Always rounds up  [4.1 → 5]

In [12]:
arr = np.array([1.34, 2.78, 3.50])

In [13]:
np.round(arr) # 1.34 → 1, 2.78 → 3, and 3.50 → 4

array([1., 3., 4.])

In [14]:
np.floor(arr) # 1.34 → 1, 2.78 → 2, and 3 → 4

array([1., 2., 3.])

In [15]:
np.ceil(arr) # 1.34 → 2, 2.78 → 3, and 3.50 → 4

array([2., 3., 4.])

In [16]:
np.pi # will return the value of pi = 3.1416....

3.141592653589793

In [17]:
# Excercise
# Given array is the list of radius of circles
# Find the area of the circles.

In [18]:

radius = np.array([2,3,4])
np.pi*radius**2

array([12.56637061, 28.27433388, 50.26548246])

In [19]:
# Element-wise arithmatic

In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [21]:
arr1 + arr2

array([5, 7, 9])

In [22]:
arr1 - arr2

array([-3, -3, -3])

In [23]:
arr1 * arr2

array([ 4, 10, 18])

In [24]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [25]:
arr1 ** arr2

array([  1,  32, 729])

In [26]:
# Comparison Operator

In [27]:
scores = np.array([32, 45, 67, 87, 23, 56, 82, 96, 87, 99, 100])

In [28]:
scores >= 40

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [29]:
scores < 40

array([ True, False, False, False,  True, False, False, False, False,
       False, False])

In [30]:
scores[scores < 40]

array([32, 23])

In [31]:
scores[scores < 40] = 0
scores

array([  0,  45,  67,  87,   0,  56,  82,  96,  87,  99, 100])