In [1]:
# Filtering = Refers to the process of selecting elements
#             from an array that match a given condition

In [2]:
import numpy as np

In [3]:
ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

In [4]:
teenegers = ages[ages<18]
teenegers

array([17, 16, 15])

In [5]:
adults = ages[(ages>18) & (ages<=65)]
print(f"Adults are {adults}")

Adults are [21 19 20 30 65 39 22 19 20 21]


In [6]:
even = ages[ages%2==0]
even

array([20, 16, 30, 18, 22, 18, 20])

In [7]:
# where(condition, array, fill) function [N.B.: The values do not match the condition will be replaced by 'fill']

In [8]:
adults = np.where(ages>=18, ages, -1)
print(adults)

[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]
