In [337]:
import numpy as np

In [338]:
rng = np.random.default_rng()

In [339]:
num = rng.integers(1,7)
print(num)

6


In [340]:
num = rng.integers(low=1, high=7)
print(num)

6


In [341]:
num = rng.integers(low=1, high=7, size=3) # 1D Array
print(num)

[6 6 5]


In [342]:
num = rng.integers(low=1, high=7, size=(3,2)) # 2D Array
print(num)

[[6 3]
 [5 3]
 [1 6]]


In [343]:
rng = np.random.default_rng(seed=1) # seed will produce the same output everytime 
num = rng.integers(low=1, high=7, size=(3,2))
print(num)

[[3 4]
 [5 6]
 [1 1]]


In [344]:
# prints a random float number between 0 and 1
random = np.random.uniform()
random

0.6149583436567602

In [345]:
# prints the random floating number between lowe and upper bound
random = np.random.uniform(low=-10, high=1)
random

-6.147493694993396

In [346]:
random = np.random.randint(low=1, high=5, size=(3, 2, 4))
random

array([[[1, 1, 4, 4],
        [1, 4, 2, 4]],

       [[2, 1, 3, 3],
        [2, 4, 2, 3]],

       [[4, 3, 3, 3],
        [1, 1, 2, 4]]], dtype=int32)

In [347]:
# Shuffle an array

In [348]:
rng = np.random.default_rng()

In [349]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([4, 5, 2, 1, 3])

In [350]:
Fruit = np.array(['🍇', '🍈', '🍉', '🍊', '🍎', '🍋‍🟩'])
Fruit = rng.choice(Fruit, size=(3, 2))
Fruit

array([['🍈', '🍊'],
       ['🍋\u200d🟩', '🍇'],
       ['🍎', '🍈']], dtype='<U3')